import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F4F6FA",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 700,
  },
  scroll: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    minHeight: 0,
  },
  container: {
    width: 420,
    maxWidth: 520,
    minWidth: 340,
    alignSelf: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 40,
    boxShadow: "0 8px 32px rgba(0,0,0,0.10)",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    marginTop: 32,
    marginBottom: 32,
  },
  title: {
    fontSize: 32,
    fontWeight: "800",
    color: "#FF7C1F",
    marginBottom: 8,
    textAlign: "center",
    letterSpacing: -0.8,
  },
  subtitle: {
    fontSize: 18,
    color: "#6B7280",
    marginBottom: 28,
    textAlign: "center",
    fontWeight: "500",
    lineHeight: 26,
  },
  input: {
    width: "100%",
    backgroundColor: "#F9FAFB",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 16,
    fontWeight: "500",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    color: "#1F2937",
    marginBottom: 16,
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
    minHeight: 44,
    // outlineStyle: "none", // No soportado en React Native Web
  },
  inputFocused: {
    borderColor: "#FF7C1F",
    backgroundColor: "#FFFFFF",
    boxShadow: "0 2px 8px rgba(255,124,31,0.10)",
  },
  passwordHint: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: -10,
    marginBottom: 10,
    lineHeight: 16,
    textAlign: "center",
    paddingHorizontal: 10,
  },
  button: {
    width: "100%",
    backgroundColor: "#FF7C1F",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
    marginBottom: 24,
    boxShadow: "0 4px 16px rgba(255,124,31,0.10)",
    minHeight: 44,
    borderWidth: 0,
  },
  buttonDisabled: {
    backgroundColor: "#FFB280",
    opacity: 0.7,
    boxShadow: "0 2px 8px rgba(255,124,31,0.05)",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E5E7EB",
  },
  dividerText: {
    color: "#6B7280",
    fontSize: 13,
    fontWeight: "600",
    paddingHorizontal: 14,
  },
  googleButton: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    marginBottom: 18,
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
    minHeight: 44,
  },
  googleButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  googleLogo: {
    width: 18,
    height: 18,
    marginRight: 10,
  },
  googleButtonText: {
    color: "#374151",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  loginPrompt: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    width: "100%",
  },
  loginPromptText: {
    color: "#6B7280",
    fontSize: 14,
    fontWeight: "500",
  },
  loginLink: {
    color: "#FF7C1F",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
});
