import { StyleSheet, Dimensions, Platform } from "react-native";
import { colors } from "src/styles";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
    position: "relative",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    flexDirection: "column",
    marginHorizontal: "auto",
    marginBottom: "auto",
    padding: 24,
    borderRadius: 24,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    width: width > 600 ? 600 : width,
    gap: 16,
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  inputsContainer: {
    width: "100%",
    height: Platform.OS === "web" ? "auto" : height * 0.15,
    flexDirection: width > 600 ? "row" : "column",
    gap: 12,
    alignItems: Platform.OS === "web" && width > 600 ? "flex-end" : "stretch",
  },
  logo: {
    margin: "auto",
    marginTop: 40,
    marginBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: colors.belandOrange,
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: {
    color: "white",
    fontWeight: "300",
    fontSize: 15,
  },
  button: {
    backgroundColor: colors.belandOrange,
    borderRadius: 12,
    paddingVertical: 14,
    width: "100%",
    shadowColor: colors.belandOrange,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  backButton: {
    position: "absolute",
    top: 40,
    left: 20,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 50,
    padding: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 10,
  },
  buttonLink: {
    paddingHorizontal: 0,
    color: "#FFFFFF",
    textDecorationLine: "none",
    fontWeight: "bold",
    fontSize: 15,
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 16,
  },
  containerRow: {
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: "auto",
    marginBottom: 30,
    marginTop: 10,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    width: width > 600 ? 600 : width - 40,
  },
  description: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 20,
  },
});
