import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F4F6FA",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 700,
  },
  scroll: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    minHeight: 0,
  },
  container: {
    width: 420,
    maxWidth: 520,
    minWidth: 340,
    alignItems: "center",
    backgroundColor: "#fff",
    paddingVertical: 40,
    paddingHorizontal: 48,
    borderRadius: 10,
    boxShadow: "0 8px 32px rgba(0,0,0,0.10)",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginTop: 32,
    marginBottom: 32,
  },
  logo: {
    width: 100,
    height: 100,
    resizeMode: "contain",
    marginBottom: 10,
  },
  title: {
    fontSize: 32,
    color: "#FF7C1F",
    fontWeight: "800",
    marginBottom: 8,
    letterSpacing: -0.8,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 18,
    color: "#6B7280",
    marginBottom: 32,
    textAlign: "center",
    fontWeight: "500",
    lineHeight: 26,
  },
  input: {
    width: "100%",
    backgroundColor: "#F9FAFB",
    borderRadius: 8,
    padding: 14,
    marginBottom: 18,
    fontSize: 16,
    fontWeight: "500",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    color: "#1F2937",
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
    // outlineStyle: "none", // No soportado en React Native Web
  },
  inputFocused: {
    borderColor: "#FF7C1F",
    backgroundColor: "#FFFFFF",
    boxShadow: "0 2px 8px rgba(255,124,31,0.10)",
  },
  button: {
    backgroundColor: "#FF7C1F",
    width: "100%",
    borderRadius: 8,
    padding: 14,
    marginTop: 10,
    alignItems: "center",
    boxShadow: "0 4px 16px rgba(255,124,31,0.10)",
    borderWidth: 0,
  },
  buttonDisabled: {
    backgroundColor: "#FFB280",
    opacity: 0.7,
    boxShadow: "0 2px 8px rgba(255,124,31,0.05)",
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginVertical: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E5E7EB",
  },
  dividerText: {
    marginHorizontal: 16,
    color: "#6B7280",
    fontSize: 14,
    fontWeight: "600",
  },
  googleButton: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    width: "100%",
    borderRadius: 8,
    padding: 14,
    alignItems: "center",
    marginBottom: 12,
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
  },
  googleButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  googleLogo: {
    width: 18,
    height: 18,
    marginRight: 10,
  },
  googleButtonText: {
    color: "#374151",
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 0.3,
  },
  demoButton: {
    backgroundColor: "#8B5CF6",
    borderRadius: 8,
    padding: 12,
    width: "100%",
    alignItems: "center",
    marginBottom: 18,
    boxShadow: "0 2px 8px rgba(139,92,246,0.10)",
  },
  demoButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 0.3,
  },
  registerPrompt: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    width: "100%",
    justifyContent: "center",
  },
  registerPromptText: {
    color: "#6B7280",
    fontSize: 15,
    fontWeight: "500",
  },
  registerLink: {
    color: "#FF7C1F",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
});
