import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  scroll: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingTop: Platform.OS === "android" ? 30 : 60, // Menos espacio en Android porque la onda está pegada al top
    paddingBottom: 40,
    minHeight: height * 0.9,
  },
  container: {
    width: "100%",
    maxWidth: Math.min(width * 0.9, 420),
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingVertical: 48,
    paddingHorizontal: 32,
    borderRadius: 24,
    elevation: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
  },
  logo: {
    width: 120,
    height: 120,
    resizeMode: "contain",
    marginBottom: 10,
  },
  title: {
    fontSize: 36,
    color: "#FF7C1F",
    fontWeight: "800",
    marginBottom: 8,
    letterSpacing: -0.8,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 18,
    color: "#6B7280",
    marginBottom: 48,
    textAlign: "center",
    fontWeight: "500",
    lineHeight: 24,
  },
  input: {
    width: "100%",
    backgroundColor: "#F9FAFB",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    fontSize: 17,
    fontWeight: "500",
    borderWidth: 2,
    borderColor: "transparent",
    color: "#1F2937",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  inputFocused: {
    borderColor: "#FF7C1F",
    backgroundColor: "#FFFFFF",
    elevation: 4,
    shadowOpacity: 0.1,
  },
  button: {
    backgroundColor: "#FF7C1F",
    width: "100%",
    borderRadius: 16,
    padding: 20,
    marginTop: 12,
    alignItems: "center",
    elevation: 8,
    shadowColor: "#FF7C1F",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  buttonDisabled: {
    backgroundColor: "#FFB280",
    opacity: 0.7,
    elevation: 4,
    shadowOpacity: 0.1,
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 18,
    letterSpacing: 0.5,
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginVertical: 32,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E5E7EB",
  },
  dividerText: {
    marginHorizontal: 20,
    color: "#6B7280",
    fontSize: 15,
    fontWeight: "600",
  },
  googleButton: {
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#E5E7EB",
    width: "100%",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    marginBottom: 16,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  googleButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  googleLogo: {
    width: 20,
    height: 20,
    marginRight: 12,
  },
  googleButtonText: {
    color: "#374151",
    fontWeight: "700",
    fontSize: 17,
    letterSpacing: 0.3,
  },
  demoButton: {
    backgroundColor: "#8B5CF6",
    borderRadius: 16,
    padding: 18,
    width: "100%",
    alignItems: "center",
    marginBottom: 24,
    elevation: 6,
    shadowColor: "#8B5CF6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
  },
  demoButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 0.3,
  },
  registerPrompt: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    width: "100%",
    justifyContent: "center",
  },
  registerPromptText: {
    color: "#6B7280",
    fontSize: 16,
    fontWeight: "500",
  },
  registerLink: {
    color: "#FF7C1F",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
});
