name: Build & Deploy

on:
  push:
    branches:
      - production
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "develop"
        type: choice
        options:
          - develop
          - sandbox
          - sandbox-b
          - production

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Copy environment file
        run: cp ${{ github.event.inputs.branch || github.ref_name }}.env .env || echo "⚠️ No env file found"

      - name: Clean node_modules
        run: |
          rm -rf node_modules node_modules/.vite
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build --quiet

      - name: Save dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.branch || github.ref_name }} # usa develop o production
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync dist s3://jetz-admin-${{ github.event.inputs.branch || github.ref_name }} --delete
