name: Build & Deploy

on:
  push:
    branches:
      - production
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "develop"
        type: choice
        options:
          - develop
          - sandbox
          - production

env:
  NODE_VERSION: 20
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Copy environment file
        run: cp ${{ github.event.inputs.branch || github.ref_name }}.env .env || echo "⚠️ No env file found"

      - name: Clean node_modules
        run: |
          rm -rf node_modules node_modules/.vite
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build --quiet

      - name: Save dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to AWS S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: jetz-admin-${{ github.event.inputs.branch || github.ref_name }}
          region: ${{ env.AWS_REGION }}
          delete: true
          source: dist
