name: CI/CD - Deploy to AWS

on:
  push:
    branches:
      - production
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "develop"
        type: choice
        options:
          - develop
          - production

env:
  NODE_VERSION: 20

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Copy environment file
        run: |
          if [ -f "${{ github.event.inputs.branch }}.env" ]; then
            cp ${{ github.event.inputs.branch }}.env .env
          else
            echo "⚠️ No env file found for ${{ github.event.inputs.branch }}"
          fi

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build --quiet

      - name: Save dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1

  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.branch }}
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test access to S3
        run: |
          echo "Checking access to bucket beland-admin-${{ github.event.inputs.branch }}"
          aws s3 ls s3://beland-admin-${{ github.event.inputs.branch }}

      - name: Sync files to S3
        run: |
          echo "Deploying files to S3 bucket beland-admin-${{ github.event.inputs.branch }}"
          aws s3 sync dist s3://beland-admin-${{ github.event.inputs.branch }} --delete

     
